doc-warnings: true
test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
  - selenium
  - needle
  - pytest
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - test
python-targets:
  - 2
  - 3