language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
before_script:
  - pytest --driver BrowserStack --capability os "OS X" --capability os_version "El Capitan" --needle-save-baseline test/
# command to run tests
script:
  - pytest --driver BrowserStack --capability os "OS X" --capability os_version "El Capitan" --doctest-modules --pep8 pytest_needle --cov pytest_needle --cov-report term-missing test/
after_success:
  - coveralls